// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RawAttr {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub raw_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntityAttrs {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub attrs: ::prost::alloc::vec::Vec<RawAttr>,
}
/// SceneDelta.effects(field 3) の要素
/// duration_ms: 0/未設定=無期限、-1=永続、>0=ミリ秒の持続時間
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TimedEffect {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub activated_at: i64,
    #[prost(int64, tag = "3")]
    pub duration_ms: i64,
    #[prost(int64, tag = "4")]
    pub flag: i64,
    #[prost(int64, tag = "5")]
    pub extra: i64,
}
/// buff_list の 1 要素 (= ZDPS の BuffEffect)。
/// event_type は EBuffEventType (1=AddTo, 2=Remove, 4=Timer, 5=StackLayer …)、
/// buff_uuid は対象バフのインスタンスキー、body_raw は LogicEffect (= BuffPayload) の bytes。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffEvent {
    #[prost(int32, tag = "1")]
    pub event_type: i32,
    #[prost(int32, tag = "2")]
    pub buff_uuid: i32,
    #[prost(int64, tag = "3")]
    pub host_uuid: i64,
    #[prost(bytes = "vec", tag = "5")]
    pub body_raw: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuffEventBatch {
    #[prost(message, repeated, tag = "2")]
    pub buffs: ::prost::alloc::vec::Vec<BuffEvent>,
}
/// BuffEvent.body_raw をラップ (= BuffEffectLogicInfo)。
/// buff_type は EffectType (18=AddBuff→BuffSnapshot / 19=BuffChange)。
/// detail_raw は型ごとにアプリ側でデコードする。
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffPayload {
    #[prost(int32, tag = "1")]
    pub buff_type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub detail_raw: ::prost::alloc::vec::Vec<u8>,
}
/// LogicEffect.EffectType==19 (BuffChange) の RawData。スタック増加/タイマー更新を表す。
/// base_id を持たず、対象は BuffEvent.buff_uuid で識別する。
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffChange {
    #[prost(int32, tag = "1")]
    pub layer: i32,
    #[prost(int64, tag = "2")]
    pub duration: i64,
    #[prost(int64, tag = "3")]
    pub create_time: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneDelta {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, optional, tag = "2")]
    pub attrs: ::core::option::Option<EntityAttrs>,
    #[prost(message, optional, tag = "10")]
    pub buff_list: ::core::option::Option<BuffEventBatch>,
    #[prost(message, optional, tag = "7")]
    pub skill_effects: ::core::option::Option<SkillImpact>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalSceneDelta {
    #[prost(message, optional, tag = "1")]
    pub base_delta: ::core::option::Option<SceneDelta>,
    #[prost(message, repeated, tag = "3")]
    pub effects: ::prost::alloc::vec::Vec<TimedEffect>,
    #[prost(int64, tag = "5")]
    pub uuid: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PlayerProfile {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
    #[prost(string, tag = "2")]
    pub account_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "35")]
    pub fight_point: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerSnapshot {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
    #[prost(message, optional, tag = "2")]
    pub char_base: ::core::option::Option<PlayerProfile>,
    #[prost(message, optional, tag = "3")]
    pub scene_data: ::core::option::Option<WorldLocation>,
    #[prost(message, optional, tag = "7")]
    pub item_package: ::core::option::Option<InvBags>,
    #[prost(message, optional, tag = "57")]
    pub r#mod: ::core::option::Option<ModuleSet>,
    #[prost(message, optional, tag = "61")]
    pub profession_list: ::core::option::Option<ClassState>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EntityVanish {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntityAppear {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(enumeration = "EntityKind", tag = "2")]
    pub ent_type: i32,
    #[prost(message, optional, tag = "3")]
    pub attrs: ::core::option::Option<EntityAttrs>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InvItem {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(int32, tag = "2")]
    pub config_id: i32,
    #[prost(int32, tag = "9")]
    pub quality: i32,
    #[prost(message, optional, tag = "13")]
    pub mod_new_attr: ::core::option::Option<ModuleAttrs>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvBags {
    #[prost(map = "int32, message", tag = "1")]
    pub packages: ::std::collections::HashMap<i32, InvBag>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModuleSet {
    #[prost(map = "int64, message", tag = "2")]
    pub mod_infos: ::std::collections::HashMap<i64, ModuleEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModuleEntry {
    #[prost(int32, repeated, tag = "4")]
    pub init_link_nums: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModuleAttrs {
    #[prost(int32, repeated, tag = "1")]
    pub mod_parts: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SocialEnvelope {
    #[prost(message, optional, tag = "1")]
    pub v_request: ::core::option::Option<SocialRequest>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SocialRequest {
    #[prost(message, optional, tag = "1")]
    pub data: ::core::option::Option<SocialBody>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InvBag {
    #[prost(map = "int64, message", tag = "4")]
    pub items: ::std::collections::HashMap<i64, InvItem>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClassState {
    #[prost(int32, tag = "1")]
    pub cur_profession_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorldLocation {
    #[prost(uint32, tag = "6")]
    pub level_map_id: u32,
    #[prost(uint32, tag = "15")]
    pub line_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkillImpact {
    #[prost(message, repeated, tag = "2")]
    pub damages: ::prost::alloc::vec::Vec<DamageRecord>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SocialBody {
    #[prost(message, optional, tag = "10")]
    pub scene_data: ::core::option::Option<WorldLocation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorldEnterSnapshot {
    #[prost(message, optional, tag = "1")]
    pub v_data: ::core::option::Option<PlayerSnapshot>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DamageRecord {
    #[prost(bool, tag = "2")]
    pub is_miss: bool,
    #[prost(enumeration = "DmgKind", tag = "4")]
    pub r#type: i32,
    #[prost(int32, tag = "5")]
    pub type_flag: i32,
    #[prost(int64, tag = "6")]
    pub value: i64,
    #[prost(int64, tag = "8")]
    pub lucky_value: i64,
    #[prost(int64, tag = "9")]
    pub hp_lessen_value: i64,
    #[prost(int64, tag = "11")]
    pub attacker_uuid: i64,
    #[prost(int32, tag = "12")]
    pub owner_id: i32,
    #[prost(bool, tag = "17")]
    pub is_dead: bool,
    #[prost(int32, tag = "18")]
    pub property: i32,
    #[prost(int64, tag = "21")]
    pub top_summoner_id: i64,
    #[prost(int32, tag = "25")]
    pub damage_mode: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorldDeltaBatch {
    #[prost(message, repeated, tag = "1")]
    pub delta_infos: ::prost::alloc::vec::Vec<SceneDelta>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorldEntityBatch {
    #[prost(message, repeated, tag = "1")]
    pub appear: ::prost::alloc::vec::Vec<EntityAppear>,
    #[prost(message, repeated, tag = "2")]
    pub disappear: ::prost::alloc::vec::Vec<EntityVanish>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LocalDeltaBatch {
    #[prost(message, optional, tag = "1")]
    pub delta_info: ::core::option::Option<LocalSceneDelta>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Vec3f {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub z: f32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CombatOrigin {
    #[prost(int32, tag = "1")]
    pub fight_source_type: i32,
    #[prost(int32, tag = "2")]
    pub source_config_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffSnapshot {
    #[prost(int32, tag = "1")]
    pub buff_uuid: i32,
    #[prost(int32, tag = "2")]
    pub base_id: i32,
    #[prost(int32, tag = "3")]
    pub level: i32,
    #[prost(int64, tag = "4")]
    pub host_uuid: i64,
    #[prost(int32, tag = "5")]
    pub table_uuid: i32,
    #[prost(int64, tag = "6")]
    pub create_time: i64,
    #[prost(int64, tag = "7")]
    pub fire_uuid: i64,
    #[prost(int32, tag = "8")]
    pub layer: i32,
    #[prost(int32, tag = "9")]
    pub part_id: i32,
    #[prost(int32, tag = "10")]
    pub count: i32,
    #[prost(int32, tag = "11")]
    pub duration: i32,
    #[prost(message, optional, tag = "12")]
    pub fight_source_info: ::core::option::Option<CombatOrigin>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuffSnapshotBundle {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub buff_infos: ::prost::alloc::vec::Vec<BuffSnapshot>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffTick {
    #[prost(int64, tag = "1")]
    pub host_uuid: i64,
    #[prost(int32, tag = "2")]
    pub buff_uuid: i32,
    #[prost(int32, tag = "3")]
    pub base_id: i32,
    #[prost(int64, tag = "4")]
    pub duration: i64,
    #[prost(int64, tag = "5")]
    pub create_time: i64,
    #[prost(int32, tag = "6")]
    pub layer: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DmgKind {
    Normal = 0,
    Miss = 1,
    Heal = 2,
}
impl DmgKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Normal => "Normal",
            Self::Miss => "Miss",
            Self::Heal => "Heal",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Normal" => Some(Self::Normal),
            "Miss" => Some(Self::Miss),
            "Heal" => Some(Self::Heal),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EntityKind {
    Unknown = 0,
    Monster = 1,
    Player = 10,
}
impl EntityKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "Unknown",
            Self::Monster => "Monster",
            Self::Player => "Player",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Unknown" => Some(Self::Unknown),
            "Monster" => Some(Self::Monster),
            "Player" => Some(Self::Player),
            _ => None,
        }
    }
}
